arm64: Add ap_init() prototype to smp.h
Add missing function prototype for ap_init() which is declared in smp.h
on other platforms. This fixes the build error:
  error: no previous prototype for 'ap_init' [-Werror=missing-prototypes]